version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    assignees:
      - BlindMaster24
    reviewers:
      - BlindMaster24
    labels:
      - dependencies
      - rust
    target-branch: main
    groups:
      cargo-patch-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      cargo-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:30"
    open-pull-requests-limit: 20
    assignees:
      - BlindMaster24
    reviewers:
      - BlindMaster24
    labels:
      - dependencies
      - github-actions
    target-branch: main
    groups:
      github-actions-all:
        patterns:
          - "*"
