[workspace]
release = false
pr_labels = ["release"]
pr_branch_prefix = "release-plz/"
release_always = false

[[package]]
name = "teamtalk"
release = true
publish = true
semver_check = true

[[package]]
name = "teamtalk-sys"
release = false
publish = false
