host_name = "darkser.ydns.eu"
port = 43961
udp_port = 43961
user_name = "kirillbot"
password = "sukabot87657373"
nick_name = "reg_bot"
client_name = "TeamtalkRegisterBot"
server_name = "kirill's server"
encrypted = false
tt_join_channel = "/"
tt_join_channel_password = ""
tt_status_text = "Online and ready to help!"
tt_gender = "female"
teamtalk_registration_broadcast_enabled = true
bot_admin_lang = "RU"
tg_bot_token = "7842603653:AAHcv707_d7zd2b44XTcJIPZAfNJY_sWL0Q"
admin_ids = [883359755, 1181331335]
verify_registration = true
web_registration_enabled = true
web_app_host = "0.0.0.0"
web_app_port = 5000
teamtalk_client_template_dir = "/home/kirill/teamtalk.py/TeamTalk_v5.18_Portable-win64"
db_name = "test.db"
telegram_deeplink_registration_enabled = true
