[package]
name = "teamtalk-macros"
version = "0.1.2"
edition = "2024"
authors = ["BlindMaster24"]
description = "Proc macros for TeamTalk bot routing"
license = "MIT"
repository = "https://github.com/BlindMaster24/TeamTalkRust"
homepage = "https://github.com/BlindMaster24/TeamTalkRust"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.117", features = ["full"] }
